#!/bin/bash

cd "$(dirname "$0")"

# https://getcomposer.org/doc/articles/autoloader-optimization.md

optimize_level="$1"

case $optimize_level in
    -l2|--level2)
    composer_arguments="--classmap-authoritative"
    ;;
    -l1|--level1)
    composer_arguments="--optimize"
    ;;
    -h|--help)
    help="1"
    ;;
    *)
    composer_arguments=""
    ;;
esac

if [ -n "$help" ]; then
    echo ""
    echo "Команда генерации автолоадера"
    echo ""
    echo "    -l1|--level1    -> composer dump-autoload --optimize"
    echo "    -l2|--level2    -> composer dump-autoload --classmap-authoritative"
    echo ""
    echo "classmap-authoritative"
    echo "Если класс не найден в classmap автолоадер считает, что его нет и не ищет его на диске"
    echo ""
    exit 1
fi

composer_command="./composer dump-autoload $composer_arguments"

echo ""
echo "Выполнение команды: $composer_command"
echo ""

./$composer_command

# laravel
#./artisan optimize –force
#./artisan config:cache
#./artisan route:cache
