version: "3"
services:

  php:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: "php-metrics-php"
    container_name: "php-metrics-php"
    volumes:
      - ./:/app
    links:
      - redis
    networks:
      - "docker_network"

  redis:
    build:
      context: ./
      dockerfile: docker/redis.Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: "php-metrics-redis"
    container_name: "php-metrics-redis"
    networks:
      - "docker_network"

networks:
  docker_network:
    driver: bridge
