version: "3"
services:

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: "php-metrics-nginx"
    container_name: "php-metrics-nginx"
    ports:
      - "8090:8080"
    volumes:
      - ./:/app
    networks:
      - "docker_network"
    links:
      - php
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: "php-metrics-php"
    container_name: "php-metrics-php"
    volumes:
      - ./:/app
      - ~/.composer/auth.json:/composer/auth.json
    links:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - "docker_network"

  redis:
    build:
      context: ./
      dockerfile: docker/redis.Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: "php-metrics-redis"
    container_name: "php-metrics-redis"
    networks:
      - "docker_network"

networks:
  docker_network:
    driver: bridge
