{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=\"up\"}, instance)"
   },
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_count{instance=~\"$host\"}[30s]))/30"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_count{instance=~\"$host\",status=~\"(4|5)..\"}[30s]))/30"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n    sum without (status)(\n        rate(app_http_memory_usage_bytes_bucket[1m])\n    )\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, \n    sum without (status)(\n        rate(app_http_memory_usage_bytes_bucket[1m])\n    )\n)",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n    sum without (status)(\n        rate(app_http_duration_seconds_bucket[1m])\n    )\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, \n    sum without (status)(\n        rate(app_http_duration_seconds_bucket[1m])\n    )\n)",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_http_memory_usage_bytes_sum{instance=\"$host\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_http_memory_usage_bytes_sum{instance=\"$host\"}[1m]))\n/\nsum(rate(app_http_memory_usage_bytes_count{instance=\"$host\"}[1m]))\n"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(app_http_requests_count{status=~\"(2)..\",instance=~\"$host\"}[1m])) > 0",
     "legendFormat": "200"
    },
    {
     "expr": "sum(irate(app_http_requests_count{status=~\"(4)..\",instance=~\"$host\"}[1m])) > 0",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(app_http_requests_count{status=~\"(5)..\",instance=~\"$host\"}[1m])) > 0",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (timer) (\n    rate(app_http_runtime_seconds[30s])\n)\n",
     "legendFormat": "{{timer}}"
    }
   ]
  },
  {
   "title": "Top",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, \n    sum(\n        increase(app_http_requests_count{instance=~\"$host\"}[$timeRange])\n    ) by (route)\n) > 0"
    }
   ]
  },
  {
   "title": "Error",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, \n    sum(\n        increase(app_http_requests_count{instance=~\"$host\",status=~\"(4|5)..\"}[$timeRange])\n    ) by (route)\n) > 0"
    }
   ]
  },
  {
   "title": "Slow",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, \n    sum by (route) (\n        rate(app_http_runtime_seconds[1m])\n    )\n    /\n    sum by (route) (\n        increase(app_http_requests_count[1m])\n    )\n)"
    }
   ]
  }
 ]
}